import { Dimensions, Platform } from "react-native";

var { height, width } = Dimensions.get("window");
export default {
  ASSETS: {
    BACK: require("./assets/back.png"),
    FACEBOOK: require("./assets/facebook.png"),
    GOOGLE: require("./assets/googleplus.png"),
    LOCATION: require("./assets/locations.png"),
    LOGO: require("./assets/logo.png"),
    MENU: require("./assets/menu.png"),
    IMG: require("./assets/img1.png"),
    IMG3: require("./assets/img3.png"),
    DISCOUNT: require("./assets/discount.png"),
    MIN: require("./assets/mins.png"),
    PLUS: require("./assets/plus.png"),
    RIGHTARROWYELLOW: require("./assets/nexxt-arrow-yellow.png"),
    RIGHTARROWWHITE: require("./assets/nexxt-arrow.png"),
    CHECK: require("./assets/check.png"),
    CLIENT: require("./assets/slient.png"),
    ONE: require("./assets/1.png"),
    INFOGRAPHIC: require("./assets/info-graphic.png"),
    FINDLOCATION: require("./assets/find-locations.png"),
    SEARCH: require("./assets/search.png"),
    MALE: require("./assets/male.png"),
    ACTIVEMALE: require("./assets/male_active.png"),
    FEMALE: require("./assets/female.png"),
    ACTIVEFEMALE: require("./assets/female-active.png"),
    PERCENT: require("./assets/discount-green.png"),
    GRAYARROW: require("./assets/nextgray.png"),
    IMAGE: require("./assets/image.png"),
    RATING: require("./assets/rating.png"),
    PROFILE: require("./assets/def-user.png"),
    PROFILEICON: require("./assets/profile.png"),
    PAYMENT: require("./assets/payment.png"),
    INVITE: require("./assets/invite.png"),
    CHAT: require("./assets/chat.png"),
    CONTACT: require("./assets/contact.png"),
    TERMS: require("./assets/tems.png"),
    SETTING: require("./assets/setting.png"),
    NEXTARROW: require("./assets/Next-arrow.png"),
    LOGOUT: require("./assets/logout.png"),
    PASSWORD: require("./assets/password-view.png"),
    CALENDAR: require("./assets/cale.png"),
  },
};
